Added dark mode switch listener on Windows
albertosottile/darkdetect pull request #20
Opened 2022-05-04 08:35 UTC by TransparentLC

Implemented with WIN32 API. See my comment in #14 for details.

2022-05-09 19:36 UTC, albertosottile commented
Hi, thank you for your contribution. The implementation is nice and clean. However, the rationale behind `darkdetect` was to have a lightweight pure-Python package, with no non-standard dependencies, that could be embedded in more complex Python projects (e.g. [Syncplay](https://github.com/syncplay/syncplay)). I feel that introducing platform specific Python wheels would break this philosophy. 

At the moment, as I mentioned in #14, this is a task that I see more suitable for the GUI library. Nevertheless, if you could manage to reimplement this code through `ctypes`, then I would definitely accept it as it would eliminate all the previously mentioned drawbacks, while still providing this valuable feature.

2022-05-11 08:10 UTC, TransparentLC commented
I have reimplemented the listener by ctypes. Feel free to try it out!

2022-05-22 09:06 UTC, albertosottile requested changes
Thank you very much for this contribution. I tested it on Windows and the code LGTM, I only have a few minor comments.

2022-05-22 09:06 UTC, albertosottile commented on README.md
> +import darkdetect, threading
Please separate the two imports on two lines, as in 
```python
import threading
import darkdetect
```

2022-05-22 09:06 UTC, albertosottile commented on darkdetect/_dummy.py
> +    raise NotImplementedError()
Please add a new line at the end of this file.

2022-05-22 09:06 UTC, albertosottile commented on darkdetect/_mac_detect.py
> +    raise NotImplementedError()
Please add a new line at the end of this file.

2022-05-22 09:58 UTC, albertosottile approved these changes

2022-05-22 09:59 UTC, merged

2022-05-22 10:00 UTC, albertosottile commented
Thank you again for this. I will try to create a new release later today.